const STORAGE_KEY = 'pennywise-data-v1';
const defaultData = { profile: null, expenses: [], savings: [], plan: { needs: 60, wants: 30, other: 10 } };
let data = loadData();
const money = value => `₹${Math.round(Number(value) || 0).toLocaleString('en-IN')}`;
const $ = id => document.getElementById(id);
function loadData() { try { return JSON.parse(localStorage.getItem(STORAGE_KEY)) || structuredClone(defaultData); } catch { return structuredClone(defaultData); } }
function persist() { localStorage.setItem(STORAGE_KEY, JSON.stringify(data)); render(); }
function totalExpenses() { return data.expenses.reduce((sum, item) => sum + Number(item.amount), 0); }
function deposited() { return data.savings.filter(item => item.type === 'saved').reduce((sum, item) => sum + Number(item.amount), 0); }
function withdrawn() { return data.savings.filter(item => item.type === 'withdrawal').reduce((sum, item) => sum + Number(item.amount), 0); }
function actualSavings() { return Math.max(0, deposited() - withdrawn()); }
function totalsByCategory(category) { return data.expenses.filter(item => item.category === category).reduce((sum, item) => sum + Number(item.amount), 0); }
function planAmounts() { const income = Number(data.profile?.income || 0); const plannedSpend = Math.max(0, income - Number(data.profile?.goal || 0)); const totalShares = Math.max(1, data.plan.needs + data.plan.wants + data.plan.other); return { savings: Number(data.profile?.goal || 0), needs: Math.round(plannedSpend * data.plan.needs / totalShares), wants: Math.round(plannedSpend * data.plan.wants / totalShares), other: Math.max(0, plannedSpend - Math.round(plannedSpend * data.plan.needs / totalShares) - Math.round(plannedSpend * data.plan.wants / totalShares)) }; }
function dateText(value) { return new Date(`${value}T12:00:00`).toLocaleDateString('en-IN', { day: 'numeric', month: 'short' }); }
function today() { return new Date().toISOString().slice(0, 10); }
function escapeHtml(text) { return String(text || '').replace(/[&<>'"]/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[char])); }
function render() {
  const profile = data.profile || { name: 'there', income: 0, goal: 0, type: 'Student' }; const plans = planAmounts(); const expenses = totalExpenses(); const saved = actualSavings(); const plannedSpend = Math.max(0, Number(profile.income) - Number(profile.goal)); const remaining = Math.max(0, plannedSpend - expenses); const progress = Number(profile.goal) ? Math.min(100, Math.round(saved / Number(profile.goal) * 100)) : 0;
  $('userName').textContent = profile.name || 'there'; $('avatar').textContent = (profile.name || 'U').charAt(0).toUpperCase(); $('incomeValue').textContent = money(profile.income); $('incomeType').textContent = profile.type || 'Personal plan'; $('goalValue').textContent = money(profile.goal); $('goalRemaining').textContent = `${money(Math.max(0, Number(profile.goal) - saved))} remaining`; $('savedValue').textContent = money(saved); $('savedProgress').textContent = `${progress}% of goal`; $('expensesValue').textContent = money(expenses); $('expenseCount').textContent = `${data.expenses.length} transaction${data.expenses.length === 1 ? '' : 's'}`;
  $('plannedSpend').textContent = money(plannedSpend); $('plannedProgress').style.width = `${plannedSpend ? Math.min(100, expenses / plannedSpend * 100) : 0}%`; $('plannedCaption').textContent = plannedSpend ? `${money(remaining)} left in your planned spending` : 'Set up your plan to see progress'; $('needsBudget').textContent = money(plans.needs); $('wantsBudget').textContent = money(plans.wants); $('otherBudget').textContent = money(plans.other); $('needsActual').textContent = `${money(totalsByCategory('Needs'))} spent`; $('wantsActual').textContent = `${money(totalsByCategory('Wants'))} spent`; $('otherActual').textContent = `${money(totalsByCategory('Other'))} spent`;
  $('safeSpend').textContent = money(remaining); const day = new Date().getDate(); const daysLeft = Math.max(1, new Date(new Date().getFullYear(), new Date().getMonth() + 1, 0).getDate() - day + 1); $('dailySpend').textContent = money(remaining / daysLeft); $('weeklySpend').textContent = money(remaining / Math.max(1, Math.ceil(daysLeft / 7))); $('guideNote').textContent = remaining ? `Try to keep your average daily spending around ${money(remaining / daysLeft)} to stay within your plan.` : 'You have used your planned spending budget. Take a breath and review your categories.';
  $('goalPercent').textContent = `${progress}%`; $('goalBar').style.width = `${progress}%`; $('goalFootRight').textContent = `${money(Math.max(0, Number(profile.goal) - saved))} to go`; $('alertBanner').textContent = saved >= Number(profile.goal) && Number(profile.goal) > 0 ? '🎉 You have reached your savings goal. That is worth celebrating.' : expenses > plannedSpend && plannedSpend > 0 ? '🔴 You have exceeded your planned spending budget. Review your wants and needs below.' : expenses > plannedSpend * .8 && plannedSpend > 0 ? '🟡 You are getting close to your planned spending limit.' : '🟢 You’re on track with your budget. Keep following your plan!'; $('alertBanner').className = `alert-banner ${expenses > plannedSpend && plannedSpend > 0 ? 'danger' : expenses > plannedSpend * .8 && plannedSpend > 0 ? 'warning' : ''}`;
  $('savingsHeroValue').textContent = money(saved); $('savingsHeroPercent').textContent = `${progress}%`; $('savingsHeroBar').style.width = `${progress}%`; $('savingsHeroGoal').textContent = `${money(profile.goal)} goal`; $('savingsHeroCaption').textContent = saved ? `${money(Math.max(0, Number(profile.goal) - saved))} more to reach your goal.` : 'Every saved amount brings you closer.'; $('depositedTotal').textContent = money(deposited()); $('withdrawnTotal').textContent = money(withdrawn()); $('savingsRemaining').textContent = money(Math.max(0, Number(profile.goal) - saved));
  renderExpenses(); renderSavings(); renderAnalysis();
}
function renderExpenses() { const filter = $('categoryFilter')?.value || 'all'; const list = data.expenses.filter(item => filter === 'all' || item.category === filter).sort((a,b) => b.date.localeCompare(a.date)); $('categorySummary').innerHTML = ['Needs','Wants','Other'].map(category => `<div><span>${category}</span><strong>${money(totalsByCategory(category))}</strong><small>${data.expenses.filter(item=>item.category===category).length} transactions</small></div>`).join(''); $('expenseList').innerHTML = list.length ? list.map(item => `<div class="expense-row"><div class="expense-symbol">${item.category === 'Needs' ? '⌂' : item.category === 'Wants' ? '♡' : '!'}</div><div class="row-main"><strong>${escapeHtml(item.name)}</strong><small>${dateText(item.date)}${item.note ? ` · ${escapeHtml(item.note)}` : ''}</small></div><span class="row-category">${item.category}</span><div class="row-amount">${money(item.amount)}</div><div class="row-actions"><button onclick="openExpense('${item.id}')" title="Edit expense">Edit</button><button onclick="deleteExpense('${item.id}')" title="Delete expense">×</button></div></div>`).join('') : '<div class="empty">No expenses here yet. Add your first one to see the pattern.</div>'; }
function renderSavings() { const list = [...data.savings].sort((a,b) => b.date.localeCompare(a.date)); $('savingsHistory').innerHTML = list.length ? list.map(item => `<div class="history-row"><div class="expense-symbol">${item.type === 'saved' ? '↗' : '↘'}</div><div class="row-main"><strong>${item.type === 'saved' ? 'Saved money' : 'Withdrawal'}</strong><small>${dateText(item.date)}${item.location ? ` · ${escapeHtml(item.location)}` : ''}${item.reason ? ` · ${escapeHtml(item.reason)}` : ''}</small></div><div class="row-amount" style="color:${item.type === 'saved' ? '#318b78' : '#b76c58'}">${item.type === 'saved' ? '+' : '-'}${money(item.amount)}</div><div></div></div>`).join('') : '<div class="empty">Your savings activity will appear here.</div>'; const p = data.profile || { income: 0, goal: 0 }; const plans = planAmounts(); $('saveSteps').innerHTML = [`Receive your monthly income — ${money(p.income)}`, `Set aside your goal first — ${money(p.goal)}`, `Keep ${money(plans.needs)} for essential needs`, `Leave ${money(plans.wants)} for wants`, 'Track every expense as it happens', 'Review your spending at month end'].map(step => `<li>${step}</li>`).join(''); }
function renderAnalysis() { const total = totalExpenses(); const needs = totalsByCategory('Needs'), wants = totalsByCategory('Wants'), other = totalsByCategory('Other'); const degree = n => total ? n / total * 360 : 0; $('donut').style.background = `conic-gradient(#48a995 0deg ${degree(needs)}deg, #f3c75c ${degree(needs)}deg ${degree(needs+wants)}deg, #9c91d8 ${degree(needs+wants)}deg 360deg)`; $('donutTotal').textContent = money(total); $('legend').innerHTML = [['Needs',needs,'#48a995'],['Wants',wants,'#f3c75c'],['Other',other,'#9c91d8']].map(x=>`<div><i style="background:${x[2]}"></i>${x[0]} <strong>${money(x[1])}</strong></div>`).join(''); const plans = planAmounts(); $('barChart').innerHTML = [['Needs',plans.needs,needs],['Wants',plans.wants,wants],['Other',plans.other,other]].map(x => `<div class="bar-line"><div><span>${x[0]}</span><strong>${money(x[2])} / ${money(x[1])}</strong></div><div class="bar-bg"><span style="width:${x[1] ? Math.min(100,x[2]/x[1]*100) : 0}%"></span></div></div>`).join(''); const highest = [['Needs',needs],['Wants',wants],['Other',other]].sort((a,b)=>b[1]-a[1])[0]; $('monthlySummary').innerHTML = [['Income',money(data.profile?.income)],['Expenses',money(total)],['Saved',money(deposited())],['Withdrawn',money(withdrawn())],['Current savings',money(actualSavings())],['Highest category',highest[1] ? highest[0] : 'None'],['Remaining balance',money(Math.max(0,Number(data.profile?.income||0)-total))],['Goal status',`${Number(data.profile?.goal) ? Math.min(100,Math.round(actualSavings()/data.profile.goal*100)) : 0}% there`]].map(x=>`<div><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join(''); }
function openModal(title, content, onSubmit) { $('modalRoot').innerHTML = `<div class="modal-backdrop"><div class="modal"><div class="modal-header"><div><h2>${title}</h2></div><button class="close-modal">×</button></div>${content}</div></div>`; $('modalRoot').querySelector('.close-modal').onclick = closeModal; $('modalRoot').querySelector('.modal-backdrop').onclick = e => { if(e.target.classList.contains('modal-backdrop')) closeModal(); }; $('modalRoot').querySelector('form').onsubmit = e => { e.preventDefault(); onSubmit(new FormData(e.target)); }; }
function closeModal() { $('modalRoot').innerHTML = ''; }
function setupModal() { const p = data.profile || {}; openModal(p.name ? 'Edit your plan' : 'Welcome to Pennywise', `<p class="muted" style="margin-bottom:18px">${p.name ? 'Keep your plan current as your life changes.' : 'A few details help us make your money plan personal.'}</p><form><div class="form-grid"><div class="field"><label>Your name</label><input name="name" value="${escapeHtml(p.name)}" placeholder="e.g. Ananya" required></div><div class="field"><label>I am a...</label><select name="type"><option ${p.type==='Student'?'selected':''}>Student</option><option ${p.type==='Working Student'?'selected':''}>Working Student</option><option ${p.type==='Employee'?'selected':''}>Employee</option></select></div><div class="form-grid two"><div class="field"><label>Monthly income / pocket money</label><input name="income" type="number" min="0" value="${p.income||''}" placeholder="15000" required></div><div class="field"><label>Monthly savings goal</label><input name="goal" type="number" min="0" value="${p.goal||''}" placeholder="5000" required></div></div><div><label class="eyebrow" style="display:block;margin:4px 0 10px">PLANNED SPENDING SPLIT</label><div class="form-grid two"><div class="field"><label>Needs share</label><input name="needs" type="number" min="0" value="${data.plan.needs}" required></div><div class="field"><label>Wants share</label><input name="wants" type="number" min="0" value="${data.plan.wants}" required></div><div class="field"><label>Other share</label><input name="other" type="number" min="0" value="${data.plan.other}" required></div></div><small class="muted">These shares divide the money left after your savings goal.</small></div></div><div class="intro-note">Your information stays on this device. Pennywise never connects to your bank or moves real money.</div><div class="modal-actions"><button class="primary-btn">${p.name ? 'Save changes' : 'Create my plan'} →</button></div></form>`, form => { data.profile = { name: form.get('name'), type: form.get('type'), income: Number(form.get('income')), goal: Number(form.get('goal')) }; data.plan = { needs: Number(form.get('needs')), wants: Number(form.get('wants')), other: Number(form.get('other')) }; persist(); closeModal(); }); }
function expenseModal(existing) { openModal(existing ? 'Edit expense' : 'Add an expense', `<form><div class="form-grid"><div class="field"><label>What did you spend on?</label><input name="name" value="${escapeHtml(existing?.name)}" placeholder="e.g. Bus pass" required></div><div class="form-grid two"><div class="field"><label>Amount</label><input name="amount" type="number" min="1" value="${existing?.amount||''}" placeholder="250" required></div><div class="field"><label>Date</label><input name="date" type="date" value="${existing?.date||today()}" required></div></div><div class="field"><label>Category</label><select name="category"><option ${existing?.category==='Needs'?'selected':''}>Needs</option><option ${existing?.category==='Wants'?'selected':''}>Wants</option><option ${existing?.category==='Other'?'selected':''}>Other</option></select></div><div class="field"><label>Note <span class="muted">(optional)</span></label><textarea name="note" placeholder="Anything useful to remember?">${escapeHtml(existing?.note)}</textarea></div></div><div class="modal-actions"><button type="button" class="secondary-btn close-modal">Cancel</button><button class="primary-btn">${existing ? 'Save expense' : 'Add expense'}</button></div></form>`, form => { const item = { id: existing?.id || crypto.randomUUID(), name: form.get('name'), amount: Number(form.get('amount')), category: form.get('category'), date: form.get('date'), note: form.get('note') }; if(existing) data.expenses = data.expenses.map(x=>x.id===existing.id?item:x); else data.expenses.push(item); persist(); closeModal(); }); }
function savingsModal(type) { const isSave = type === 'saved'; openModal(isSave ? 'Save money' : 'Withdraw from savings', `<p class="muted" style="margin-bottom:18px">${isSave ? 'Record money you have actually set aside.' : `You currently have ${money(actualSavings())} in savings. You cannot withdraw more than that.`}</p><form><div class="form-grid"><div class="field"><label>Amount</label><input name="amount" type="number" min="1" max="${isSave?'':actualSavings()}" required></div><div class="field"><label>Date</label><input name="date" type="date" value="${today()}" required></div>${isSave ? '<div class="field"><label>Where did you save it?</label><select name="location"><option>Bank</option><option>Cash</option><option>Other</option></select></div>' : '<div class="field"><label>Reason</label><input name="reason" placeholder="e.g. Unexpected repair" required></div>'}<div class="field"><label>Optional note</label><textarea name="note"></textarea></div></div><div id="withdrawHint" class="intro-note">${isSave ? 'This is a record only. No bank transfer will happen.' : `After this withdrawal, your savings will be updated.`}</div><div class="modal-actions"><button type="button" class="secondary-btn close-modal">Cancel</button><button class="primary-btn">${isSave ? 'Record savings' : 'Withdraw savings'}</button></div></form>`, form => { const amount = Number(form.get('amount')); if(!isSave && amount > actualSavings()) { $('withdrawHint').textContent = '❌ You cannot withdraw more than your current saved amount.'; $('withdrawHint').style.color = '#b35e4a'; return; } data.savings.push({ id: crypto.randomUUID(), type, amount, date: form.get('date'), location: form.get('location'), reason: form.get('reason'), note: form.get('note') }); persist(); closeModal(); }); }
function switchView(view) { document.querySelectorAll('.view').forEach(x=>x.classList.remove('active-view')); $(`${view}View`).classList.add('active-view'); document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active', x.dataset.view === view)); }
function openExpense(id) { expenseModal(data.expenses.find(x=>x.id===id)); } function deleteExpense(id) { if(confirm('Delete this expense?')) { data.expenses = data.expenses.filter(x=>x.id!==id); persist(); } }
$('editSetup').onclick = setupModal; $('editPlan').onclick = setupModal; $('addExpense').onclick = () => expenseModal(); $('saveMoney').onclick = () => savingsModal('saved'); $('withdrawSavings').onclick = () => savingsModal('withdrawal'); $('categoryFilter').onchange = renderExpenses; $('checkAfford').onclick = () => { const price = Number($('affordPrice').value), name = $('affordName').value || 'This purchase', remaining = Math.max(0, Number(data.profile?.income||0) - totalExpenses() - price), goal = Number(data.profile?.goal||0), result = $('affordResult'); if(!price) { result.textContent='Enter an item and price to check your plan.'; return; } result.className = `afford-result ${price <= Math.max(0, Number(data.profile?.income||0)-totalExpenses())*.25 ? 'safe' : price <= remaining && actualSavings() >= goal*.5 ? 'careful' : 'no'}`; result.textContent = result.className.includes('safe') ? `🟢 ${name} fits within your current spending plan.` : result.className.includes('careful') ? `🟡 You can afford ${name}, but it may reduce what you can save this month.` : `🔴 ${name} may exceed your planned spending and affect your savings goal.`; }; $('resetData').onclick = () => { if(confirm('Clear your Pennywise data and start again?')) { localStorage.removeItem(STORAGE_KEY); data = structuredClone(defaultData); setupModal(); render(); } }; document.querySelectorAll('[data-view]').forEach(button => button.onclick = () => switchView(button.dataset.view));
 $('dateLabel').textContent = new Date().toLocaleDateString('en-IN',{month:'long',year:'numeric'}).toUpperCase(); $('monthName').textContent = new Date().toLocaleDateString('en-IN',{month:'long'}); render(); if(!data.profile) setupModal();
